#!/bin/bash

### INSTALL PYTHON35 ###
if [ ! -d "${OPENSHIFT_DATA_DIR}bin" -o ! -x ${OPENSHIFT_DATA_DIR}bin/python3 ]; then
    cd ${OPENSHIFT_TMP_DIR}
    wget https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tar.xz
    tar xf Python-3.5.2.tar.xz
    cd Python-3.5.2
    ./configure --prefix=${OPENSHIFT_DATA_DIR}
    make && make install
fi

### INSTALL PIP ###
if [ ! -x ${OPENSHIFT_DATA_DIR}bin/pip3 ]; then
    cd ${OPENSHIFT_TMP_DIR}
    wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
    ${OPENSHIFT_DATA_DIR}bin/python3 get-pip.py
    ${OPENSHIFT_DATA_DIR}bin/pip3 install --upgrade pip
fi

# cleanup
rm -rf ${OPENSHIFT_TMP_DIR}/*
