#!/bin/bash

export BLAS=${OPENSHIFT_DATA_DIR}lib/libfblas.a
export LAPACK=${OPENSHIFT_DATA_DIR}lib/liblapack.a

### INSTALL PYTHON PACKAGEs ###
if [ -f ${OPENSHIFT_REPO_DIR}requirements.txt ]; then
    ${OPENSHIFT_DATA_DIR}bin/pip3 install -r ${OPENSHIFT_REPO_DIR}requirements.txt --no-cache-dir
fi

cd ${OPENSHIFT_DATA_DIR}

### CREATE NOTEBOOK DIR ###
if [ ! -d ${OPENSHIFT_DATA_DIR}notebook ] ; then
    mkdir -p ${OPENSHIFT_DATA_DIR}notebook
fi

if [ ! -d ${OPENSHIFT_DATA_DIR}.jupyter ] ; then
    mkdir -p ${OPENSHIFT_DATA_DIR}.jupyter
fi

if [ ! -d ${OPENSHIFT_DATA_DIR}.ipython ] ; then
    mkdir -p ${OPENSHIFT_DATA_DIR}.ipython
fi

if [ -d ${OPENSHIFT_REPO_DIR}config ]; then
    cp -fa ${OPENSHIFT_REPO_DIR}config/* ${OPENSHIFT_DATA_DIR}.jupyter/
fi

### CLEANUP ###
rm -rf ${OPENSHIFT_TMP_DIR}/*

