#!/bin/bash

export PATH=${OPENSHIFT_DATA_DIR}bin:$PATH

export JUPYTER_DATA_DIR=${OPENSHIFT_DATA_DIR}
export JUPYTER_PATH=${OPENSHIFT_DATA_DIR}.jupyter
export JUPYTER_RUNTIME_DIR=${OPENSHIFT_TMP_DIR}
export JUPYTER_CONFIG_DIR=${OPENSHIFT_DATA_DIR}.jupyter

cd ${OPENSHIFT_DATA_DIR}

jupyter nbextension enable --user --py widgetsnbextension
jupyter nbextensions_configurator enable --user

jupyter contrib nbextension install --user
