#!/bin/bash

export PATH=${OPENSHIFT_DATA_DIR}bin:$PATH

export JUPYTER_DATA_DIR=${OPENSHIFT_DATA_DIR}
export JUPYTER_PATH=${OPENSHIFT_DATA_DIR}.jupyter
export JUPYTER_RUNTIME_DIR=${OPENSHIFT_TMP_DIR}
export JUPYTER_CONFIG_DIR=${OPENSHIFT_DATA_DIR}.jupyter

cd ${OPENSHIFT_DATA_DIR}

if [ "x${OPENSHIFT_POSTGRESQL_DB_URL}" != 'x' ]; then
    export DATABASE_URL="${OPENSHIFT_POSTGRESQL_DB_URL}/${OPENSHIFT_APP_NAME}"
    LANG=en_US.UTF-8 pgcontents init -l $DATABASE_URL --no-prompt
fi

jupyter nbextension enable --user --py widgetsnbextension
jupyter nbextensions_configurator enable --user

jupyter contrib nbextension install --user
