#!/bin/bash

PATH=${OPENSHIFT_DATA_DIR}bin:$PATH

JUPYTER_DATA_DIR=${OPENSHIFT_DATA_DIR}
JUPYTER_PATH=${OPENSHIFT_DATA_DIR}.jupyter
JUPYTER_RUNTIME_DIR=${OPENSHIFT_TMP_DIR}
JUPYTER_CONFIG_DIR=${OPENSHIFT_DATA_DIR}.jupyter

cd ${OPENSHIFT_DATA_DIR}

jupyter nbextension enable --user --py widgetsnbextension
jupyter nbextensions_configurator enable --user

jupyter contrib nbextension install --user
