#!/bin/bash

export PATH=${OPENSHIFT_DATA_DIR}bin:$PATH

export IPYTHONDIR=${OPENSHIFT_DATA_DIR}.ipython

export JUPYTER_DATA_DIR=${OPENSHIFT_DATA_DIR}
export JUPYTER_PATH=${OPENSHIFT_DATA_DIR}.jupyter
export JUPYTER_RUNTIME_DIR=${OPENSHIFT_TMP_DIR}
export JUPYTER_CONFIG_DIR=${OPENSHIFT_DATA_DIR}.jupyter

cd ${OPENSHIFT_DATA_DIR}

jupyter notebook \
	--no-browser \
	--ip=${OPENSHIFT_DIY_IP} \
	--port=${OPENSHIFT_DIY_PORT} \
	--log-level=DEBUG \
	notebook \
	> ${OPENSHIFT_DIY_LOG_DIR}server.log 2>&1 &
